### ISSUE TITLE
[1주차] 진행사항

### ISSUE THREAD

**Issue by saseungmin** [saseungmin/Recoil_Todo_Backend#8]
### 📌  1주차 진행사항
- [x] recoil-todo backend를 위한 koa setting #1 
- [x] eslint, jest등 필요한 dependencies install #1 
- [x] CI / CD 구성 #3 
- [x] Codecov에 코드 커버리지 #1
- [x] heroku에 서버 배포 #2 #3 
- [x] mongo cloud 서버인 mongo atlas 서버 구성 #4 
- [x] mongoose를 사용한 mongoDB 연결 #4 
- [x] 회원가입 api 구현 #6 
- [x] 회원가입시 jsonwebtoken(JWT) 사용하기 #7 
    - 쿠키 사용(5일 후 만료)
    - 2일 남았을 시 쿠키 만료 기간 5일 후로 변경
- [x] login 구현 #9 
- [x] logout 구현 #10 
- [x] 로그인시 유저정보 체크 #10
